import {useNavigate} from "react-router";
import {logoutUser} from "~/appwrite/auth";
import { useLoaderData } from "react-router";
import { getUser } from "~/appwrite/auth";
import { Link } from "react-router";
import {Outlet} from "react-router";
import { useSearchParams } from "react-router";
import { PagerComponent } from "@syncfusion/ej2-react-grids";
import { getAllTrips } from "~/appwrite/trips";
import { parseTripData } from "../../../lib/utils";
import { TripCard } from "../../../components";

import { type LoaderFunctionArgs } from "react-router";

export const loader = async ({ request }: LoaderFunctionArgs) => {
    const limit = 8;

    const url = new URL(request.url);
    const page = parseInt(url.searchParams.get("page") || "1", 10);

    const offset = (page - 1) * limit;

    const { allTrips, total } = await getAllTrips(limit, offset);

    return {
        trips: allTrips.map((trip) => {
            const parsedData = parseTripData(trip.tripDetail) || {};

            return {
                id: trip.$id,
                ...parsedData,
                imageUrls: trip.imageUrls ?? [],
            };
        }),
        total,
    };
};
const TravelPage = ({ loaderData }: any) => {
    const trips = loaderData.trips || [];
    const [searchParams, setSearchParams] = useSearchParams();

    const currentPage = Number(
        searchParams.get("page") || "1"
    );

    const handlePageChange = (page: number) => {
        setSearchParams((prev) => {
            prev.set("page", String(page));
            return prev;
        });

        setTimeout(() => {
            document
                .querySelector(".created-trips")
                ?.scrollIntoView({
                    behavior: "smooth",
                    block: "start",
                });
        }, 50);
    };
    return (
        <>
        <section className="relative h-screen overflow-hidden">

            <img
                src="/assets/images/hero.jpg"
                alt="hero"
                className="absolute inset-0 w-full h-full object-cover"
            />

            <div
                className="absolute inset-0
                        bg-gradient-to-r
                        from-white/90
                        via-white/60
                        to-transparent"
            />

            <div className="relative z-10 h-full flex items-center">
                <div className="max-w-[1400px] mx-auto w-full px-12">
                    <div className="max-w-3xl">
                        <h1 className="
                            text-5xl
                            md:text-6xl
                            lg:text-7xl
                            font-bold
                            leading-tight
">
                            Plan Your Next Adventure With AI
                        </h1>

                        <p className="text-xl text-dark-100/90 mt-6">
                            Discover personalized travel experiences generated by AI,
                            tailored to your interests, budget and travel style.
                        </p>

                        <Link
                            to="/create-trip"
                            className="mt-8 inline-block bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-xl"
                        >
                            Try Generating AI Trips
                        </Link>
                    </div>
                </div>

            </div>

        </section>
            <section className="created-trips bg-white py-20">
                <div className="max-w-[1400px] mx-auto px-6 md:px-12">

                <h2 className="text-4xl font-bold mb-8">
                    Created Trips
                </h2>

                {trips.length === 0 ? (
                    <div className="text-center py-20">
                        <h3 className="text-2xl font-semibold">
                            No trips yet
                        </h3>

                        <Link
                            to="/create-trip"
                            className="mt-4 inline-block bg-blue-600 text-white px-6 py-3 rounded-xl"
                        >
                            Create your first trip
                        </Link>
                    </div>
                ) : (
                    <div className="trip-grid mb-4">
                        {trips.map((trip: any) => (
                            <TripCard
                                key={trip.id}
                                id={trip.id}
                                name={trip.name || "AI Travel Plan"}
                                imageUrl={trip.imageUrls?.[0]}
                                location={
                                    trip.itinerary?.[0]?.location ??
                                    trip.destination ??
                                    ""
                                }
                                tags={[
                                    trip.interests,
                                    trip.travelStyle,
                                ].filter(Boolean)}
                                price={trip.estimatedPrice || "TBD"}
                            />
                        ))}
                    </div>

                )}
            <PagerComponent
                totalRecordsCount={loaderData.total}
                pageSize={8}
                currentPage={currentPage}
                click={(args) => handlePageChange(args.currentPage)}
                cssClass="!mt-8"
            />
            </div>

        </section>
    </>
    );

}
export default TravelPage
