import {useNavigate} from "react-router";
import {logoutUser} from "~/appwrite/auth";
import { useLoaderData } from "react-router";
import { getUser } from "~/appwrite/auth";
import { Link } from "react-router";
import {Outlet} from "react-router";
import { useSearchParams } from "react-router";
import { PagerComponent } from "@syncfusion/ej2-react-grids";
import { getAllTrips, getTripsByUser } from "~/appwrite/trips";
import { parseTripData } from "../../../lib/utils";
import { TripCard } from "../../../components";
import Typed from "typed.js";
import {useEffect, useRef} from "react";
import { type LoaderFunctionArgs } from "react-router";

export const clientLoader = async () => {
    const limit = 8;
    const offset = 0;
    const user = await getUser();

    const [userTrips, { allTrips, total }] = await Promise.all([
        user ? getTripsByUser(user.accountId) : Promise.resolve([]),
        getAllTrips(limit, offset),
    ]);
    console.log("USER TRIPS =", userTrips);
    const  myTrips = userTrips.map((trip) => {
        const parsedData = parseTripData(trip.tripDetail) || {};

        return {
            id: trip.$id,
            ...parsedData,
            imageUrls: trip.imageUrls ?? [],
        };
    })

    return {
        myTrips,
        trips: allTrips.map((trip) => {
            const parsedData = parseTripData(trip.tripDetail) || {};
            return {
                id: trip.$id,
                ...parsedData,
                imageUrls: trip.imageUrls ?? [],
            };
        }),
        total,
    };
};

clientLoader.hydrate = true;

const TravelPage = ({ loaderData }: any) => {
    const trips = loaderData.trips || [];
    const myTrips = loaderData.myTrips || [];
    const [searchParams, setSearchParams] = useSearchParams();

    const currentPage = Number(
        searchParams.get("page") || "1"
    );

    const handlePageChange = (page: number) => {
        setSearchParams((prev) => {
            prev.set("page", String(page));
            return prev;
        });

        setTimeout(() => {
            document
                .querySelector(".created-trips")
                ?.scrollIntoView({
                    behavior: "smooth",
                    block: "start",
                });
        }, 50);
    };
    const typedRef = useRef<HTMLSpanElement>(null);


    useEffect(() => {
        if (!typedRef.current) return;
        const typed = new Typed(typedRef.current!, {
            strings: [
                "Adventure With AI",
                "Business Week",
                "Family Vacation",
                "Luxury Trip",
                "Budget Journey",
            ],
            typeSpeed: 60,
            backSpeed: 40,
            backDelay: 1800,
            loop: true,
            smartBackspace: true,
            showCursor: true,
            cursorChar: "|",
        });

        return () => typed.destroy();
    }, []);

    return (
        <>
        <section className="relative h-screen overflow-hidden">

            <img
                src="/assets/images/hero.jpg"
                alt="hero"
                className="absolute inset-0 w-full h-full object-cover"
            />

            <div
                className="absolute inset-0
                        bg-gradient-to-r
                        from-white/90
                        via-white/60
                        to-transparent"
            />

            <div className="relative z-10 h-full flex items-center">
                <div className="max-w-[1400px] mx-auto w-full px-12">
                    <div className="max-w-3xl">
                        <h1
                            className="
        text-5xl
        md:text-6xl
        lg:text-7xl
        font-bold
        leading-tight
    "
                        >
                            Plan Your Next
                            <br />

                            <span ref={typedRef}></span>
                        </h1>

                        <p className="text-xl text-dark-100/90 mt-6">
                            Discover personalized travel experiences generated by AI,
                            tailored to your interests, budget and travel style.
                        </p>

                        <Link
                            to="/create-trip"
                            className="mt-8 inline-block bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-xl"
                        >
                            Try Generating AI Trips
                        </Link>
                    </div>
                </div>

            </div>

        </section>
            <section className="bg-white pt-20">
                <div className="max-w-[1400px] mx-auto px-6 md:px-12">

                    <div className="flex items-center justify-between mb-8">
                        <div>
                            <h2 className="text-4xl font-bold">
                                Continue Your Journey
                            </h2>

                            <p className="text-gray-500 mt-2">
                                Your recently created AI trips.
                            </p>
                        </div>

                    </div>

                    {myTrips.length === 0 ? (
                        <div className="text-center py-16 border rounded-2xl">
                            <h3 className="text-2xl font-semibold">
                                You haven't created any trips yet.
                            </h3>

                            <p className="text-gray-500 mt-3">
                                Generate your first AI itinerary.
                            </p>
                        </div>
                    ) : (
                        <div className="trip-grid">
                            {myTrips.map((trip: any) => (
                                <TripCard
                                    key={trip.id}
                                    id={trip.id}
                                    name={trip.name}
                                    imageUrl={trip.imageUrls?.[0]}
                                    location={trip.itinerary?.[0]?.location ?? ""}
                                    tags={[
                                        trip.interests,
                                        trip.travelStyle,
                                    ].filter(Boolean)}
                                    price={trip.estimatedPrice}
                                />
                            ))}
                        </div>
                    )}
                </div>
            </section>
            <section className="created-trips bg-white py-20">
                <div className="max-w-[1400px] mx-auto px-6 md:px-12">

                <h2 className="text-4xl font-bold mb-8">
                    Created Trips
                </h2>

                {trips.length === 0 ? (
                    <div className="text-center py-20">
                        <h3 className="text-2xl font-semibold">
                            No trips yet
                        </h3>

                        <Link
                            to="/create-trip"
                            className="mt-4 inline-block bg-blue-600 text-white px-6 py-3 rounded-xl"
                        >
                            Create your first trip
                        </Link>
                    </div>
                ) : (
                    <div className="trip-grid mb-4">
                        {trips.map((trip: any) => (
                            <TripCard
                                key={trip.id}
                                id={trip.id}
                                name={trip.name || "AI Travel Plan"}
                                imageUrl={trip.imageUrls?.[0]}
                                location={
                                    trip.itinerary?.[0]?.location ??
                                    trip.destination ??
                                    ""
                                }
                                tags={[
                                    trip.interests,
                                    trip.travelStyle,
                                ].filter(Boolean)}
                                price={trip.estimatedPrice || "TBD"}
                            />
                        ))}
                    </div>

                )}
            <PagerComponent
                totalRecordsCount={loaderData.total}
                pageSize={8}
                currentPage={currentPage}
                click={(args) => handlePageChange(args.currentPage)}
                cssClass="!mt-8"
            />
            </div>

        </section>
    </>
    );

}
export default TravelPage
